#Application URL-UAT Environment
url = https://www.automationexercise.com/


#Browser Configuration
browser = chrome

#Implicait wait
implicitWait = 2

#Explicit Wait
explicitWait = 20

validEmail=david123@yopmail.com
validPassword=David@1234
userNameOnNavBar = David Hopper

invalidEmail=smith@yopmail.com
invalidPassword=Smith@123

invalidLoginAttemptMsg = Your email or password is incorrect!

AccountCreateMessage = Congratulations! Your new account has been success

